# Use a Maven image to build the application
FROM jelastic/maven:3.9.4-openjdk-22.ea-b17 AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml and source code into the container
COPY pom.xml .
COPY src ./src

# Download dependencies and build the application
RUN mvn dependency:go-offline && mvn clean package -DskipTests

# Use a JDK image to run the application
FROM jelastic/maven:3.9.4-openjdk-22.ea-b17

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/target/chat-application-0.0.1-SNAPSHOT.jar ./app.jar

# Expose port 8080
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app/app.jar"]